name: Check Swagger after Merge or Manually

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  check-swagger:
    runs-on: ubuntu-latest

    steps:
    - name: Check Swagger Status
      id: swagger_check
      run: |
        STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://api.yoyaklery.site/swagger)
        echo "HTTP_STATUS=$STATUS" >> $GITHUB_ENV
        if [ "$STATUS" -ne 200 ]; then
          echo "Swagger status check failed with $STATUS"
          echo "SWAGGER_FAIL=true" >> $GITHUB_ENV
        else
          echo "SWAGGER_FAIL=false" >> $GITHUB_ENV
        fi

    - name: Send Slack Alert if Swagger Failed
      if: env.SWAGGER_FAIL == 'true'
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_COLOR: '#ff0000'
        SLACK_MESSAGE: |
          âŒ Swagger ë¬¸ì„œ ì‘ë‹µ ì‹¤íŒ¨!
          - URL: https://api.yoyaklery.site/swagger
          - ì‘ë‹µ ì½”ë“œ: ${{ env.HTTP_STATUS }}
          - ë¸Œëœì¹˜: ${{ github.ref }}
          - ì»¤ë°‹: ${{ github.sha }}
        SLACK_TITLE: "ğŸš¨ Swagger ìƒíƒœ ì²´í¬ ì‹¤íŒ¨"
        SLACK_USERNAME: 'Swagger Bot'